# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8751982b6ee2f1fe17f541f79adc3359b147b5e934e062bb9d358485ee9ddd7208f9b80468e450ca8cc3103dcd80d11da46d141108ad10b82db21a74ae0f7af4

test:
  secret_key_base: 2c16f37ca654fd032782532f8b2cd6212a83caaa2b14d3d7abaadb80c05a05a2e963a388dbac01546631a611bb6dd77cbd18a6c8bf705b490315315412f8aff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
